# src/config.py

# Multi-language dictionary for UI localization
TRANS = {
    "zh": {
        "APP_TITLE": "AutoLabel Pro: 智能标注 & 自动推理",
        "BTN_LOAD_DIR": "📂 加载 Dataset 目录",
        "BTN_LOAD_MODEL": "⚖️ 加载已训练模型 (.pt/.pth)",
        "BTN_TRAIN": "🚀 开始训练",
        "BTN_STOP_TRAIN": "⏹ 停止训练",
        "LBL_STRATEGY": "训练策略选择:",
        "MODE_TRANSFER": "1. 迁移学习 (基于官方预训练)",
        "MODE_RECURSIVE": "2. 迭代增强 (基于上一轮效果)",
        "MODE_SCRATCH": "3. 从零训练 (放弃预权重)",
        "GRP_PARAMS": "参数设置",
        "LBL_EPOCHS": "训练轮数 (Epochs):",
        "LBL_FREEZE": "冻结层数 (Freeze):",
        "LBL_THRESH": "自动训练阈值:",
        "GRP_MONITOR": "训练监控",
        "TIP_READY": "准备就绪",
        "LBL_BASE_MODEL": "基础模型 (Base Model)",
        "MENU_EXPORT": "导出 (Export)",
        "MENU_IMPORT": "导入 (Import)",
        "MENU_LANG": "语言 (Language)",
        "ACT_IMPORT_COCO": "导入 COCO JSON 标签",
        "ACT_IMPORT_VOC": "导入 Pascal VOC (.xml) 标签",
        "ACT_EXPORT_VOC": "导出 Pascal VOC (.xml)",
        "ACT_EXPORT_COCO": "导出 COCO Detection (.json)",
        "TIPS_HTML": """<b>[ 基础导航 ]</b><br>A / D : 上一张 / 下一张 (自动保存)<br>J : 移至废弃 (Junk)<br><br><b>[ 画布操作 ]</b><br>R : 切换 画框 / 编辑 模式<br>中键按住 : 拖拽画布 (抓手)<br>Ctrl + 滚轮 : 缩放视图<br><br><b>[ 编辑快捷键 ]</b><br>Ctrl + C / V : 复制 / 粘贴<br>Ctrl + D : 快速克隆<br>Ctrl + Z : 撤销<br>Delete : 删除选中框""",
        "TIP_TRANSFER": "加载所选基础模型，保留通用特征，适合刚开始标注",
        "TIP_RECURSIVE": "加载上一轮训练出的 best.pt，不断累积经验",
        "TIP_SCRATCH": "仅加载所选基础模型的网络结构，不加载权重。适合特殊纹理或数据量大时",
        "TIP_MODEL_SELECT": "选择 YOLO 或 Torchvision 基础模型架构",
        "FMT_PROGRESS": "训练进度: {}/{}",
        "FMT_STARTING": "训练进度: 0/{} (正在启动...)",
        "LBL_TOTAL_RESET": "累计已训: 0 轮 (新数据集)",
        "FMT_TOTAL_STATS": "累计已训: {} 轮 (覆盖 {} 张)",
        "STATUS_MANUAL": "数据状态: ✅ [人工已标]",
        "STATUS_AI": "数据状态: 🤖 [AI 推理]",
        "STATUS_TRAIN_STOPPED": "状态: 训练已手动终止",
        "CTX_EDIT_LABEL": "✏️ 修改标签",
        "CTX_DEL_BOX": "🗑️ 删除此框",
        "DLG_LABEL_TITLE": "编辑标签",
        "DLG_CLS_TITLE": "初始化数据集类别",
        "DLG_CLS_MSG": "检测到新数据集。请选择或输入需要标注的类别：",
        "DLG_CLS_HINT": "(支持多选，用逗号分隔，例如: person, car)",
        "DLG_BTN_CLEAR": "清空输入",
        "DLG_BTN_OK": "确定",
        "DLG_BTN_CANCEL": "取消",
        "DLG_QUICK_ADD": "快速添加 COCO 类别:",
        "MSG_CONFIRM_STOP": "确定要强制终止当前训练吗？\n(未保存的进度将丢失)",
        "MSG_NO_DATASET": "请先加载数据集！",
        "MSG_EXPORT_SUCCESS": "成功导出 {} 张图片到:\n{}",
        "MSG_IMPORT_CONFIRM": "导入操作将覆盖同名文件，是否继续？",
        "MSG_IMPORT_SUCCESS": "导入成功！\n共处理了 {} 个文件。",
        "MSG_MODEL_LOADED": "模型就绪: {}",
        "MSG_MODEL_FAIL": "加载失败: {}",
        "MSG_ONNX_MODE": "已加载 ONNX 模型 (仅推理，不可训练)",
        "LBL_PROMPT_TITLE": "YOLO-World 提示词:",
        "TIP_PROMPT_INPUT": "输入提示词，用逗号分隔 (Zero-Shot)。例如: giant panda, bear",
        "PH_PROMPT": "例如: giant panda, safety helmet",
    },
    "en": {
        "APP_TITLE": "KeenForge: Smart Labeling & Auto-Infer",
        "BTN_LOAD_DIR": "📂 Load Dataset Dir",
        "BTN_LOAD_MODEL": "⚖️ Load Trained Model (.pt/.pth)",
        "BTN_TRAIN": "🚀 Start Training",
        "BTN_STOP_TRAIN": "⏹ Stop Training",
        "LBL_STRATEGY": "Training Strategy:",
        "MODE_TRANSFER": "1. Transfer Learning (Base on Official)",
        "MODE_RECURSIVE": "2. Recursive Learning (Base on Best)",
        "MODE_SCRATCH": "3. Train from Scratch (No Weights)",
        "GRP_PARAMS": "Parameters",
        "LBL_EPOCHS": "Epochs:",
        "LBL_FREEZE": "Freeze Layers:",
        "LBL_THRESH": "Auto-Train Threshold:",
        "GRP_MONITOR": "Monitor",
        "TIP_READY": "Ready",
        "LBL_BASE_MODEL": "Base Model",
        "MENU_EXPORT": "Export",
        "MENU_IMPORT": "Import",
        "MENU_LANG": "Language",
        "ACT_IMPORT_COCO": "Import COCO JSON Labels",
        "ACT_IMPORT_VOC": "Import Pascal VOC (.xml) Labels",
        "ACT_EXPORT_VOC": "Export Pascal VOC (.xml)",
        "ACT_EXPORT_COCO": "Export COCO Detection (.json)",
        "TIPS_HTML": """<b>[ Navigation ]</b><br>A / D : Prev / Next (Auto Save)<br>J : Move to Junk<br><br><b>[ Canvas Ops ]</b><br>R : Toggle Draw / Edit Mode<br>Middle Click : Pan Canvas (Hand)<br>Ctrl + Scroll : Zoom<br><br><b>[ Shortcuts ]</b><br>Ctrl + C / V : Copy / Paste<br>Ctrl + D : Duplicate<br>Ctrl + Z : Undo<br>Delete : Remove Selected""",
        "TIP_TRANSFER": "Loads selected base model weights. Best for starting new projects.",
        "TIP_RECURSIVE": "Loads 'best.pt' from previous training to accumulate learning.",
        "TIP_SCRATCH": "Loads architecture only (no weights). Best for large data or unique textures.",
        "TIP_MODEL_SELECT": "Select YOLO or Torchvision base architecture",
        "FMT_PROGRESS": "Progress: {}/{}",
        "FMT_STARTING": "Progress: 0/{} (Starting...)",
        "LBL_TOTAL_RESET": "Total Trained: 0 Rounds (New Dataset)",
        "FMT_TOTAL_STATS": "Total Trained: {} Rounds ({} Images)",
        "STATUS_MANUAL": "Data Status: ✅ [Manual Labeled]",
        "STATUS_AI": "Data Status: 🤖 [AI Inference]",
        "STATUS_TRAIN_STOPPED": "Status: Training Stopped Manually",
        "CTX_EDIT_LABEL": "✏️ Edit Label",
        "CTX_DEL_BOX": "🗑️ Delete Box",
        "DLG_LABEL_TITLE": "Edit Label",
        "DLG_CLS_TITLE": "Initialize Dataset Classes",
        "DLG_CLS_MSG": "New dataset detected. Please select or enter classes:",
        "DLG_CLS_HINT": "(Multi-select supported, comma separated, e.g.: person, car)",
        "DLG_BTN_CLEAR": "Clear Input",
        "DLG_BTN_OK": "OK",
        "DLG_BTN_CANCEL": "Cancel",
        "DLG_QUICK_ADD": "Quick Add COCO Class:",
        "MSG_CONFIRM_STOP": "Are you sure to stop training?\n(Unsaved progress will be lost)",
        "MSG_NO_DATASET": "Please load a dataset first!",
        "MSG_EXPORT_SUCCESS": "Successfully exported {} images to:\n{}",
        "MSG_IMPORT_CONFIRM": "Import will overwrite existing files. Continue?",
        "MSG_IMPORT_SUCCESS": "Import Success!\nProcessed {} files.",
        "MSG_MODEL_LOADED": "Model Loaded: {}",
        "MSG_MODEL_FAIL": "Load Failed: {}",
        "MSG_ONNX_MODE": "ONNX Model Loaded (Inference Only)",
        "LBL_PROMPT_TITLE": "YOLO-World Prompt:",
        "TIP_PROMPT_INPUT": "Enter class names separated by comma for Zero-Shot detection. E.g.: giant panda, bear",
        "PH_PROMPT": "e.g. giant panda, safety helmet",
    }
}

# Standard COCO class list
COCO_CLASSES = [
    "person", "bicycle", "car", "motorcycle", "airplane", "bus", "train", "truck", "boat", "traffic light",
    "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat", "dog", "horse", "sheep", "cow",
    "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella", "handbag", "tie", "suitcase", "frisbee",
    "skis", "snowboard", "sports ball", "kite", "baseball bat", "baseball glove", "skateboard", "surfboard",
    "tennis racket", "bottle", "wine glass", "cup", "fork", "knife", "spoon", "bowl", "banana", "apple",
    "sandwich", "orange", "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair", "couch",
    "potted plant", "bed", "dining table", "toilet", "tv", "laptop", "mouse", "remote", "keyboard", "cell phone",
    "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors", "teddy bear",
    "hair drier", "toothbrush"
]