# src/config.py

TRANS = {
    "zh": {
        "APP_TITLE": "KeenForge: 智能标注与自动推理",
        "BTN_LOAD_DIR": "加载数据集",
        "BTN_LOAD_MODEL": "加载已训练模型 (.pt/.pth)",
        "BTN_CLEANING": "数据清洗",
        "BTN_DEDUP": "数据除重",
        "BTN_CLUSTER": "相似分组",
        "TIP_DEDUP": "只做重复图片检测与移除（不聚类）",
        "TIP_CLUSTER": "按相似度把图片分组，每组选 1 张代表优先标注",
        "BTN_TRAIN": "开始训练",
        "BTN_STOP_TRAIN": "停止训练",
        "LBL_STRATEGY": "训练策略:",
        "MODE_TRANSFER": "1. 迁移学习 (基于官方权重)",
        "MODE_RECURSIVE": "2. 递归学习 (基于最优权重)",
        "MODE_SCRATCH": "3. 从零训练 (不加载权重)",
        "GRP_PARAMS": "参数设置",
        "LBL_EPOCHS": "Epochs:",
        "LBL_FREEZE": "冻结层数:",
        "LBL_THRESH": "自动训练阈值:",
        "GRP_MONITOR": "训练监控",
        "TIP_READY": "就绪",
        "LBL_BASE_MODEL": "基础模型",
        "MENU_EXPORT": "导出",
        "MENU_IMPORT": "导入",
        "MENU_LANG": "语言",
        "ACT_IMPORT_COCO": "导入 COCO JSON 标签",
        "ACT_IMPORT_VOC": "导入 Pascal VOC (.xml) 标签",
        "ACT_EXPORT_VOC": "导出 Pascal VOC (.xml)",
        "ACT_EXPORT_COCO": "导出 COCO 检测 (.json)",
        "TIPS_HTML": "<b style='color:#0056b3;'>导航</b><br><span style='color:#555;'>A / D&nbsp;&nbsp;上一张 / 下一张 (自动保存)<br>J&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;移到垃圾文件夹</span><br><br><b style='color:#0056b3;'>画布操作</b><br><span style='color:#555;'>R&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;切换绘制 / 编辑模式<br>Space+拖拽&nbsp;&nbsp;平移画布<br>Ctrl+滚轮&nbsp;&nbsp;缩放</span><br><br><b style='color:#0056b3;'>快捷键</b><br><span style='color:#555;'>Ctrl+C / V&nbsp;&nbsp;复制 / 粘贴<br>Ctrl+D&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;复制选中框<br>Ctrl+Z&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;撤销<br>Delete&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;删除选中框</span>",
        "TIP_TRANSFER": "加载所选基础模型权重，适合新项目起步。",
        "TIP_RECURSIVE": "加载上一轮训练的 best.pt 继续累积学习。",
        "TIP_SCRATCH": "仅加载网络结构（不加载权重），适合大数据或特殊纹理。",
        "TIP_MODEL_SELECT": "选择 YOLO 或 Torchvision 基础模型架构",
        "FMT_PROGRESS": "训练进度: {} 张",
        "FMT_STARTING": "训练进度: 0/{} (正在启动...)",
        "LBL_TOTAL_RESET": "累计已训: 0 轮 (新数据集)",
        "FMT_TOTAL_STATS": "累计已训: {} 轮 (覆盖 {} 张)",
        "STATUS_MANUAL": "数据状态: 人工标注",
        "STATUS_AI": "数据状态: AI 推理",
        "STATUS_TRAIN_STOPPED": "状态: 训练已手动停止",
        "CTX_EDIT_LABEL": "编辑标签",
        "CTX_DEL_BOX": "删除框",
        "DLG_LABEL_TITLE": "编辑标签",
        "DLG_CLS_TITLE": "初始化数据集类别",
        "DLG_CLS_MSG": "检测到新数据集，请选择或输入类别:",
        "DLG_CLS_HINT": "(支持多选，逗号分隔，例如: person, car)",
        "DLG_BTN_CLEAR": "清空输入",
        "DLG_BTN_OK": "确定",
        "DLG_BTN_CANCEL": "取消",
        "DLG_QUICK_ADD": "快速添加 COCO 类别:",
        "MSG_CONFIRM_STOP": "确定要停止训练吗？\n(未保存的进度将丢失)",
        "MSG_NO_DATASET": "请先加载数据集！",
        "MSG_EXPORT_SUCCESS": "成功导出 {} 张图片到:\n{}",
        "MSG_IMPORT_CONFIRM": "导入将覆盖现有文件，是否继续？",
        "MSG_IMPORT_SUCCESS": "导入成功！\n已处理 {} 个文件。",
        "MSG_MODEL_LOADED": "模型已加载: {}",
        "MSG_MODEL_FAIL": "加载失败: {}",
        "MSG_ONNX_MODE": "ONNX 模型已加载（仅推理）",
        "LBL_PROMPT_TITLE": "YOLO-World 提示词:",
        "TIP_PROMPT_INPUT": "输入类别名（逗号分隔）进行零样本检测，例如: giant panda, bear",
        "PH_PROMPT": "例如: giant panda, safety helmet",
        # ==== 以下为语言统一新增 key (zh) ====
        "TTL_ERROR": "错误",
        "TTL_WARNING": "警告",
        "TTL_SUCCESS": "成功",
        "TTL_CONFIRM": "确认",
        "TTL_INFO": "提示",
        "TTL_UPDATE": "训练完成",
        "TTL_CLASSES_UPDATED": "类别已更新",
        "TTL_CRASH": "崩溃",
        "TTL_ONNX": "ONNX 模式",
        "TTL_STOP_TRAINING": "停止训练",
        "TTL_SELECT_EXPORT_DIR": "选择导出目录",
        "TTL_SAVE_COCO": "保存 COCO JSON",
        "TTL_SELECT_JSON": "选择 JSON 文件",
        "TTL_SELECT_XML_DIR": "选择 XML 文件夹",
        "TTL_SELECT_MODEL": "选择模型",
        "TTL_SELECT_DATASET": "选择数据集目录",
        "TTL_CLUSTER_DONE": "聚类完成",
        "TTL_CLUSTER_FAIL": "聚类失败",
        "TTL_REMOVE_CONFIRM": "确认移除",
        "FMT_MAP50": "mAP50\n{0}",
        "FMT_LOSS": "损失\n{0}",
        "MON_MAP50": "mAP50",
        "MON_LOSS": "损失",
        "MON_EPOCH": "轮次",
        "MON_EPOCH_FMT": "{0} / {1}",
        "MON_BADGE_READY": "就绪",
        "MON_BADGE_TRAINING": "训练中",
        "MON_BADGE_DONE": "完成",
        "MON_BADGE_FAILED": "失败",
        "FMT_EPOCH": "训练轮次 {0}/{1}",
        "FMT_RUNTIME": "运行时间: {0:.4f} 小时",
        "FMT_LOG_EPOCH": "[Ep {0}/{1}] mAP: {2:.3f} | 损失: {3:.3f}",
        "FMT_DONE_IN": "完成，耗时 {0:.4f} 小时",
        "FMT_STATUS_TRAINING": "训练中: {0} · Epochs {1} · Freeze {2}",
        "FMT_ROUND_REP_PROGRESS": "第{0}轮代表样本: {1}/{2} 已标注",
        "FMT_ROUND_QUOTA": "第{0}轮标注进度: {1}/{2}（代表 {3} + 补充 {4}）· 还差 {5} 张",
        "FMT_ROUND_MISSING": " · 待处理: {0}",
        "FMT_ROUND_REPS_DONE": "第{0}轮代表已全部标注 · 点击 [开始训练] 或等待弹窗",
        "MSG_ROUND_WAIT_TRAINING": "第{0}轮标注已完成，但第{1}轮模型仍在训练中。\n\n为避免训练进程互相覆盖，本轮训练将在当前模型跑完后自动弹出。你的标注已保存，无需重新操作。",
        "FMT_ROUND_WAIT_TRAINING": "第{0}轮已就绪 · 等待当前训练结束后自动开始",
        "FMT_CLUSTER_SAVED": "已生成 {0} 个多样性聚类",
        "FMT_LABEL_SETUP_UPDATED": "标签设置已更新: {0}",
        "FMT_ROUND_ALL_DONE": "第 {0} 轮代表已全部标注 · 请训练",
        "FMT_ROUND_ACTIVE": "第 {0} 轮 · 请标注 {1} 个簇代表（完整列表已显示，代表置顶）",
        "FMT_FULL_LIST_RESTORED": "已恢复完整列表 ({0} 张) · 可手动标注或训练",
        "FMT_REMAINING_NO_CLUSTER": "剩余 {0} 张未标注，无需聚类。",
        "FMT_REMAINING_MANUAL": "剩余 {0} 张未标注，请手动完成剩余标注。",
        "FMT_ROUND_DONE_TITLE": "第 {0} 轮训练完成 — 下一轮标注",
        "FMT_RECLUSTER_STATUS": "正在重新聚类 · 目标 {0} 簇...",
        "FMT_RECLUSTER_FEATURES": "重新聚类中 · 目标 {0} 簇 · 提取特征...",
        "FMT_RECLUSTER_THRESHOLD": "重新聚类中 · 阈值 {0} · 生成簇...",
        "FMT_ROUND_CLUSTERED": "第 {0} 轮 · 阈值 {1} {2} 簇",
        "FMT_RECLUSTER_FAILED": "重新聚类失败: {0}",
        "FMT_REMOVED_DUPS": "已移除 {0} 张重复图片，数据集现有 {1} 张",
        "FMT_DIVERSE_ORDER": "已按多样性排序，前 {0} 张为代表样本",
        "FMT_LIST_STATS": "共 {0} 张 · 已标 {1} 张 · 待标 {2} 张",
        "FMT_FILE_REP": "[代表#{0} 人标] {1}",
        "FMT_FILE_REP_TIP": "簇#{0} · 代表性样本 · 优先人工标注",
        "FMT_FILE_AI": "[簇#{0} AI待标] {1}",
        "FMT_FILE_AI_TIP": "簇#{0} · 训练后 AI 自动标注",
        "PH_FIND_IMAGE": "查找图片…（回车跳到第一张匹配）",
        "TIP_FIND_IMAGE": "按文件名筛选右侧图片列表；回车跳转到第一张匹配的图片",
        "FMT_LIST_FILTER": "筛选 {0}/{1} 张",
        "FMT_FILE_UNGROUPED": "[未分组] {0}",
        "FMT_ROUND_PRODUCT": "· 第 {0} 轮训练产物",
        "FMT_ROUND_MAP": "· mAP {0:.3f}",
        "MSG_STATUS_DRAW_MODE": "绘制模式：拖动拉框，拉完自动回到编辑模式 (R 切换)",
        "MSG_STATUS_EDIT_MODE": "编辑模式：点击/拖动已有框移动调整 · 拉新框按 R (R 切换)",
        "MSG_STATUS_STOPPED": "已停止",
        "MSG_USER_STOPPED": "!!! 用户手动停止训练 !!!",
        "MSG_STATUS_EXPORTING_XML": "正在导出 XML...",
        "MSG_STATUS_EXPORT_XML_DONE": "XML 导出完成",
        "MSG_STATUS_EXPORTING_JSON": "正在导出 JSON...",
        "MSG_STATUS_EXPORT_JSON_DONE": "JSON 导出完成",
        "MSG_STATUS_IMPORTING": "正在导入...",
        "MSG_STATUS_IMPORT_DONE": "导入完成: {0} 个文件",
        "MSG_EXPORT_FAILED": "导出失败: {0}",
        "MSG_IMPORT_FAILED": "导入失败: {0}",
        "MSG_LOADING_TRAINED": "加载训练模型: {0} ...",
        "MSG_LOADING_BASE": "加载/下载基础模型: {0} ...",
        "MSG_LOAD_FAILED": "加载失败:\n{0}",
        "MSG_BTN_ONNX_NOTRAIN": "ONNX（仅推理）",
        "MSG_MODEL_LOADED_SUCCESS": "模型已加载: {0}\n模式: 递归学习",
        "MSG_STATUS_MOVED_JUNK": "已移到垃圾: {0}",
        "MSG_MOVE_FAILED": "移动失败:\n{0}",
        "MSG_STATUS_NO_IMAGES": "没有剩余图片",
        "MSG_IMAGES_FOLDER_NOT_FOUND": "图片文件夹不存在！",
        "MSG_NO_IMAGES_FOUND": "文件夹中没有图片！",
        "MSG_END_OF_LIST": "列表末尾",
        "MSG_NO_ANNOTATED_DATA": "没有已标注数据。",
        "MSG_STATUS_TRAINING": "训练中...",
        "MSG_STATUS_INITIALIZING": "初始化中...",
        "MSG_STATUS_STARTING": "正在启动...",
        "MSG_LOG_TRAIN_CONNECTED": ">>> 训练进程已连接...",
        "MSG_LOG_MODEL_SAVED": ">>> 模型已保存: {0}",
        "MSG_TRAINING_DONE": "训练完成！\n已保存: {0}",
        "TTL_TRAIN_REPORT": "训练完成",
        "MSG_TRAIN_REPORT": "第 {0} 轮训练完成\n\n训练图片：{1} 张\nmAP50：{2:.3f}\n用时：{3:.1f} 分钟\n模型文件：{4}",
        "MSG_DATA_YAML_FAILED": "写入 data.yaml 失败，训练未启动：{0}",
        "TTL_TRAIN_SUMMARY": "训练全程总结",
        "SUM_DATASET": "数据集: 共 {0} 张图片 · 已全部标注完成 ✓",
        "SUM_ROUNDS": "训练轮次: 共 {0} 轮（第 {1} 轮 ~ 第 {2} 轮）",
        "SUM_BEST": "最佳模型: {0} · 第 {1} 轮 · mAP {2:.3f}",
        "SUM_DEPLOYED": "当前部署: {0}（自动部署历史最高分）",
        "SUM_TH_ROUND": "轮次",
        "SUM_TH_TIME": "完成时间",
        "SUM_TH_MODEL": "模型文件",
        "SUM_TH_IMAGES": "图片数",
        "SUM_TH_DURATION": "用时(分)",
        "SUM_TOTAL_TIME": "总训练用时: {0} 分钟",
        "SUM_FOOTER": "整个「标注 → 训练 → 再标注」迭代流程已完成，模型文件保存在 weights 目录。",
        "SUM_BTN_CLOSE": "关闭",
        "SUM_BOXES": "标注框: 共 {0} 个 · 覆盖 {1} 类",
        "SUM_BOXES_TITLE": "各类别标注框统计",
        "SUM_TH_CLASS": "类别",
        "SUM_TH_BOXES": "框数",
        "SUM_TH_SHARE": "占比",
        "MSG_STATUS_ERROR": "错误",
        "MSG_STATUS_FAILED": "失败",
        "MSG_LOG_ERROR": "!!! 错误: {0}",
        "MSG_NEW_CLASSES": "新类别: {0}",
        "MSG_SKIPPED_CLASSES": "以下类别名无效（少于2个字符或含非法字符），已跳过、未生成类别: {0}",
        # dialogs.py 补充
        "DLG_PH_CLASS": "类别名称",
        "DLG_BTN_GROUP": "组 ID",
        "DLG_PH_DESC": "描述（可选）",
        "DLG_CHK_DIFFICULT": "难例",
        "DLG_COMBO_SELECT": "--- 选择 ---",
        "DLG_PH_CLASS_EXAMPLES": "person, car, ...",
        "LBLST_TITLE": "设置标签 — AI 辅助标注",
        "LBLST_HEADER": "设置标签\n定义数据集的类别，并选择是否用 AI 协助标注。",
        "LBLST_DET_TRAINED": "检测: 数据集已有训练好的模型\n 可用训练模型自动预标注剩余图片（推荐开启），只需检查修正。",
        "LBLST_DET_COCO": "检测: {0} 个类别中 {1} 个与 COCO 常见类别重叠 ({2:.0f}%) — [{3}]\n 模型能识别这些物体，推荐开启 AI 预标注辅助。",
        "LBLST_DET_NOMATCH": "检测: 类别 [{0}] 与 COCO 常见类别无重叠\n 小众数据集，AI 预测质量差，建议纯手工标注（可自行开启）。",
        "LBLST_CHK_AI": "使用 AI 预标注辅助（首轮 YOLO-World / 后续轮训练模型）",
        "LBLST_LBL_CLASSES": "类别 (逗号分隔):",
        "LBLST_PH_CLASSES": "person, car, ...",
        "LBLST_LBL_COCO": "从 COCO 快速添加:",
        "LBLST_BTN_CLEAR": "清空",
        "LBLST_BTN_START": "开始标注",
        "LBLST_BTN_CANCEL": "取消",
        "LBLST_BTN_MOVE_UP": "上移",
        "LBLST_BTN_MOVE_DOWN": "下移",
        "LBLST_BTN_RENAME": "重命名",
        "LBLST_BTN_DELETE": "删除",
        "LBLST_BTN_ADD": "添加",
        "MSG_RENAME_TITLE": "重命名类别",
        "MSG_RENAME_PROMPT": "输入新名称:",
        "MSG_CLASS_EXISTS": "类别已存在",
        "MSG_CLASS_EMPTY": "类别不能为空",
        "MSG_DELETE_CLASS_CONFIRM": "确定删除类别「{0}」？\n已有标注中该类别对应的框将被移除。",
        "MSG_CLASS_MAPPED": "类别已更新：\n已重映射 {0} 个标签文件，移除 {1} 个框。",
        "MSG_CLASS_CHANGED_TRAIN": "类别已变更，旧训练模型与新类别不匹配。\n请重新训练后再使用 AI 预标注。",
        "CLN_TITLE": "数据清洗向导",
        "CLN_TITLE_DEDUP": "数据除重",
        "CLN_TITLE_CLUSTER": "多样性聚类",
        "CLN_STEP1_ONLY": "移除完全重复的图片",
        "CLN_BTN_FINISH_DEDUP": "完成除重",
        "CLN_BTN_PREV": "上一步",
        "CLN_BTN_NEXT": "下一步",
        "CLN_BTN_FINISH": "完成，开始标注",
        "CLN_BTN_CANCEL": "取消",
        "CLN_STEP1_TITLE": "第 1 步：移除完全重复的图片\n自动检测字节级重复、像素级重复、旋转/翻转变体。（此步使用固定感知哈希，无需选择模型）",
        "CLN_BTN_SCAN": "开始扫描",
        "CLN_BTN_CONFIRM_REMOVE": "确认移除选中",
        "CLN_BTN_SKIP": "跳过，保留全部",
        "CLN_STEP2_TITLE": "第 2 步：设置聚类分组\n把剩余图片按相似度分组，每组选 1 张代表优先标注。代表标注后训练模型，AI 自动标注同组其余图片。",
        "CLN_LBL_FEATURE_MODEL": "特征模型:",
        "CLN_LBL_THRESHOLD": "相似度阈值:",
        "CLN_LBL_THRESHOLD_HINT": "(≥此相似度归为一组)",
        "CLN_THRESHOLD_EXPLAIN": "阈值越高 分组越细(组数越多)；越低 分组越粗。\n例如 0.85 = 相似度≥85% 的图归为一组。",
        "CLN_BTN_CLUSTER": "开始聚类",
        "CLN_STEP3_TITLE": "第 3 步：聚类结果预览",
        "CLN_GPU_NONE": "无独立显卡(集成显卡)",
        "CLN_GPU_UNKNOWN": "未知",
        "CLN_REC_GPU": "检测到独立显卡，推荐 ResNet-50 (GPU 加速)",
        "CLN_REC_RAM": "内存充足 (≥16GB)，推荐 EfficientNet-B0 (更准)",
        "CLN_REC_LOWMEM": "低内存环境，推荐 MobileNetV3 (最快)",
        "CLN_HARDWARE_FMT": "已检测: {0} · {1:.0f}GB RAM\n {2}",
        "CLN_STEP2_1": "第 1 步 / 共 2 步：设置聚类分组",
        "CLN_STEP2_2": "第 2 步 / 共 2 步：聚类结果预览",
        "CLN_STEP3_1": "第 1 步 / 共 3 步：移除完全重复的图片",
        "CLN_STEP3_2": "第 2 步 / 共 3 步：设置聚类分组",
        "CLN_STEP3_3": "第 3 步 / 共 3 步：聚类结果预览",
        "CLN_MSG_FIRST_REMOVE": "请先确认移除或跳过。",
        "CLN_MSG_FIRST_CLUSTER": "请先完成聚类。",
        "CLN_MSG_LOAD_DATASET": "请先加载数据集！",
        "CLN_STATUS_SCANNING": "正在扫描重复图片...",
        "CLN_STATUS_SCAN_DONE": "扫描完成",
        "CLN_L1": "L1 字节级重复",
        "CLN_L2": "L2 像素级重复",
        "CLN_L3": "L3 旋转/翻转变体",
        "CLN_STATS_TOTAL": "总图片: {0} | 耗时: {1:.1f} 秒",
        "CLN_DUP_FOUND": "发现 {0} 组重复",
        "CLN_DUP_FOUND_TAIL": "合计将移除 {0} 张，保留 {1} 张代表",
        "CLN_NO_DUP": "未发现重复图片，可直接进入下一步。",
        "CLN_GROUP_FMT": "组{0}: {1} {2}",
        "CLN_BLURRY": "模糊图片 (低质量提示): {0} 张",
        "CLN_MSG_NO_SELECTION": "没有选中任何重复图片。",
        "CLN_REMOVE_CONFIRM_BODY": "将 {0} 张重复图片移到 _removed_duplicates/ 文件夹？\n{1}\n(每组保留代表图, 不会物理删除, 可手动恢复)",
        "CLN_REMOVED_MARK": "已移除",
        "CLN_REMOVED_STATUS": "已确认移除 {0} 张，点击\"下一步\"继续。",
        "CLN_SKIPPED_STATUS": "已跳过移除，保留全部图片。点击\"下一步\"继续。",
        "CLN_REMAINING_FMT": "将参与聚类的图片: {0} 张",
        "CLN_REMAINING_REMOVED": "(已移除 {0} 张)",
        "CLN_CLUSTER_REF": "参考聚类值: {0} 张图片 建议约 {1} 簇 (≈5%)\n首轮标注约 {1} 张代表图（每组 1 张）",
        "CLN_MSG_TOO_FEW": "图片太少，无需聚类。",
        "CLN_STATUS_CLUSTERING": "正在聚类...",
        "CLN_STATUS_CLUSTERING_PROG": "正在聚类... ({0}/{1})",
        "CLN_STATUS_TEXT_HEAD": "共 {0} 组，{1} 张图片全部有归属。",
        "CLN_STATUS_TEXT_MAX": "最大组占比 {0:.0f}% — 面积越大代表该组图片越多。",
        "CLN_STATUS_TEXT_REF": "参考聚类值: 建议约 {0} 簇 (≈5% of {1})，首轮标注约 {0} 张代表图。",
        "CLN_STATUS_TEXT_DEVIATION": "\n 当前 {0} 簇与参考 {1} 簇偏差较大，可降低/提高相似度阈值后重新聚类。",
        "CLN_TREEMAP_ITEM_3": "簇{0}\n{1}张\n{2:.0f}%",
        "CLN_TREEMAP_ITEM_2": "簇{0}\n{1:.0f}%",
        "CLN_TREEMAP_ITEM_1": "簇{0}",
        "CLN_TREEMAP_TITLE": "聚类数据分布 (共 {0} 组, {1} 张)",
        "CLN_MSG_ERROR": "操作失败:\n{0}",
        "CLN_PHASE_CACHE": "复用缓存特征 ...",
        "CLN_PHASE_EXTRACT": "提取特征中 ...",
        "CLN_PHASE_THRESH": "自动搜索阈值 {0:.3f} ...",
        "CLN_EMBED_MOBILE": "MobileNetV3 (最快, CPU友好)",
        "CLN_EMBED_EFFICIENT": "EfficientNet-B0 (更准, 质量/算力比最佳)",
        "CLN_EMBED_RESNET": "ResNet-50 (最强, 需GPU更佳)",
        # training_dialog
        "TD_TITLE": "训练设置",
        "TD_HEADER_FIRST": "首轮训练 · 数据集已标注 {0}/{1} 张\n开始第一次模型训练",
        "TD_HEADER_ROUND": "第 {0} 轮训练触发\n本轮新标注 {1} 张 · 数据集已标注 {2}/{3} 张",
        "TD_HEADER_LAST": "\n上一轮模型: {0}{1}{2}",
        "TD_LBL_MODEL": "模型:",
        "TD_HINT_ITERATE": "基于上一轮模型迭代训练（自动加载 best 权重）",
        "TD_HINT_MODEL_PICK": "默认选择历史最高 mAP 模型；也可下拉选择基础模型（如 yolo11n）",
        "TD_GRP_PARAMS": "参数设置",
        "TD_LBL_EPOCHS": "Epochs:",
        "TD_LBL_FREEZE": "Freeze 层数:",
        "TD_BTN_TRAIN": "开始训练",
        "TD_BTN_CANCEL": "取消",
        "TD_BTN_BROWSE": "浏览…",
        "TD_TIP_BROWSE": "选择自选的模型权重文件（.pt/.pth）作为训练起点",
        "TD_CUSTOM_PREFIX": "自选: {0}",
        # training_worker
        "WRK_INIT_ENV": "正在初始化训练环境...",
        "WRK_START_TORCH": "开始 PyTorch 训练: {0}",
        "WRK_START_YOLO": "开始 YOLO 训练: {0}",
        "WRK_LOAD_MODEL": "加载模型: {0}",
        "WRK_DOWNLOAD_WEIGHTS": "正在下载模型权重 {0} ...",
        "WRK_USE_LOCAL": "使用本地模型: {0}",
        "WRK_DOWNLOAD_ULTRALYTICS": "正在从 ultralytics 下载... (可能需要网络)",
        "WRK_MODEL_LOAD_FAIL": "模型加载失败: {0}。请将 {1}.pt 放到项目根目录。",
        "WRK_BEST_NOT_FOUND": "训练失败: 未找到 best.pt",
        # inference_engine
        "INF_LOAD_ERROR": "模型加载错误: {0}",
        "INF_NO_DETECTIONS": "（无检测结果）",
        "INF_YOLO_FMT": "YOLO: {0} | {1:.1f}ms",
        "INF_FAILED": "推理失败",
        "FMT_SUGGEST_BOX": "检测到相似目标 {0} → 已画出建议框，请修改类别",
        "MSG_NO_DETECTIONS": "未检测到任何目标（0 个预测框）",
        # model_wrappers
        "WRAP_LOAD_ERROR": "加载错误",
        "WRAP_CLASSIC_FOUND": "经典模型识别: {0}",
        "WRAP_ONNX_FOUND": "ONNX 识别: {0}",
        # data_cleaner phases
        "PHASE_DEDUP": "字节级去重 (SHA-256) ...",
        "PHASE_BLUR": "模糊检测 ...",
        "PHASE_HASH": "计算哈希 ({0}) ...",
        "PHASE_EXTRACT_FEAT": "提取特征 ({0}) ...",
        "PHASE_EXTRACT": "提取 ({0}) ...",
        "PHASE_INDEX": "构建检索索引 ...",
        "MSG_STATUS_DONE": "完成",
        "MSG_CRASH_OPEN_LOG": "打开日志: {0}\n{1}",
        "FMT_TARGET_CLUSTERS": "目标簇数:",
        "MSG_BTN_RECLUSTER": "重新聚类并开始标注",
        "MSG_BTN_VIEW_ALL": "查看全部图片",
        "MSG_NO_DATASET_LOADED": "未加载数据集",
        "FMT_REMAINING_TOO_FEW": "剩余 {0} 张未标注 — 不足 {1} 张，无法聚类",
        "BTN_LABEL_SETUP": "标签设置",
        "BTN_SUMMARY": "训练总结",
        "SUM_NO_HISTORY": "还没有训练记录",
        "BTN_IMPORT": "导入标签",
        "BTN_EXPORT": "导出标签",
        "BTN_MODEL": "加载模型",
        "BTN_LANG": "语言",
        "FMT_MAP50_SUFFIX": "· mAP50: {0:.3f}",
        "FMT_EPOCHS_SUFFIX": "· {0} epochs",
        "BTN_MODEL_OWN": "加载自己的模型",
        "BTN_MODEL_OWN_FILE": "从文件选择…",
        "BTN_MODEL_BASE": "基础模型",
        "BTN_MODEL_WORLD": "World 模型 (零样本)",
        "MSG_NO_TRAINED_MODEL": "(无已训练模型)",
        "LBL_AI_ASSIST": "AI 预标注辅助",
        "TIP_AI_ASSIST": "开启后，无标签图片会自动用 AI 预标注",
        "LBL_COMPARE": "模型比对（青色虚线）",
        "TIP_COMPARE": "开启后，已标注的图片也会跑一遍模型；预测框用青色虚线显示，不会被写入标签文件。移动或缩放预测框即视为采纳，会转为人工标注。",
    },
    "en": {
        "APP_TITLE": "KeenForge: Smart Labeling & Auto-Infer",
        "BTN_LOAD_DIR": "Load Dataset Dir",
        "BTN_LOAD_MODEL": "Load Trained Model (.pt/.pth)",
        "BTN_CLEANING": "Data Cleaning",
        "BTN_DEDUP": "Deduplicate",
        "BTN_CLUSTER": "Group Similar",
        "TIP_DEDUP": "Detect and remove duplicate images only (no clustering)",
        "TIP_CLUSTER": "Group similar images; label one representative per group",
        "BTN_TRAIN": "Start Training",
        "BTN_STOP_TRAIN": "Stop Training",
        "LBL_STRATEGY": "Training Strategy:",
        "MODE_TRANSFER": "1. Transfer Learning (Base on Official)",
        "MODE_RECURSIVE": "2. Recursive Learning (Base on Best)",
        "MODE_SCRATCH": "3. Train from Scratch (No Weights)",
        "GRP_PARAMS": "Parameters",
        "LBL_EPOCHS": "Epochs:",
        "LBL_FREEZE": "Freeze Layers:",
        "LBL_THRESH": "Auto-Train Threshold:",
        "GRP_MONITOR": "Monitor",
        "TIP_READY": "Ready",
        "LBL_BASE_MODEL": "Base Model",
        "MENU_EXPORT": "Export",
        "MENU_IMPORT": "Import",
        "MENU_LANG": "Language",
        "ACT_IMPORT_COCO": "Import COCO JSON Labels",
        "ACT_IMPORT_VOC": "Import Pascal VOC (.xml) Labels",
        "ACT_EXPORT_VOC": "Export Pascal VOC (.xml)",
        "ACT_EXPORT_COCO": "Export COCO Detection (.json)",
        "TIPS_HTML": "<b style='color:#0056b3;'>Navigation</b><br><span style='color:#555;'>A / D&nbsp;&nbsp;Prev / Next (Auto Save)<br>J&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Move to Junk</span><br><br><b style='color:#0056b3;'>Canvas</b><br><span style='color:#555;'>R&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Toggle Draw / Edit<br>Space+Drag&nbsp;&nbsp;Pan Canvas<br>Ctrl+Wheel&nbsp;&nbsp;Zoom</span><br><br><b style='color:#0056b3;'>Shortcuts</b><br><span style='color:#555;'>Ctrl+C / V&nbsp;&nbsp;Copy / Paste<br>Ctrl+D&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Duplicate Box<br>Ctrl+Z&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Undo<br>Delete&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Remove Box</span>",
        "TIP_TRANSFER": "Loads selected base model weights. Best for starting new projects.",
        "TIP_RECURSIVE": "Loads 'best.pt' from previous training to accumulate learning.",
        "TIP_SCRATCH": "Loads architecture only (no weights). Best for large data or unique textures.",
        "TIP_MODEL_SELECT": "Select YOLO or Torchvision base architecture",
        "FMT_PROGRESS": "Progress: {} labeled",
        "FMT_STARTING": "Progress: 0/{} (Starting...)",
        "LBL_TOTAL_RESET": "Total Trained: 0 Rounds (New Dataset)",
        "FMT_TOTAL_STATS": "Total Trained: {} Rounds ({} Images)",
        "STATUS_MANUAL": "Data Status: [Manual Labeled]",
        "STATUS_AI": "Data Status: [AI Inference]",
        "STATUS_TRAIN_STOPPED": "Status: Training Stopped Manually",
        "CTX_EDIT_LABEL": "Edit Label",
        "CTX_DEL_BOX": "Delete Box",
        "DLG_LABEL_TITLE": "Edit Label",
        "DLG_CLS_TITLE": "Initialize Dataset Classes",
        "DLG_CLS_MSG": "New dataset detected. Please select or enter classes:",
        "DLG_CLS_HINT": "(Multi-select supported, comma separated, e.g.: person, car)",
        "DLG_BTN_CLEAR": "Clear Input",
        "DLG_BTN_OK": "OK",
        "DLG_BTN_CANCEL": "Cancel",
        "DLG_QUICK_ADD": "Quick Add COCO Class:",
        "MSG_CONFIRM_STOP": "Are you sure to stop training?\n(Unsaved progress will be lost)",
        "MSG_NO_DATASET": "Please load a dataset first!",
        "MSG_EXPORT_SUCCESS": "Successfully exported {} images to:\n{}",
        "MSG_IMPORT_CONFIRM": "Import will overwrite existing files. Continue?",
        "MSG_IMPORT_SUCCESS": "Import Success!\nProcessed {} files.",
        "MSG_MODEL_LOADED": "Model Loaded: {}",
        "MSG_MODEL_FAIL": "Load Failed: {}",
        "MSG_ONNX_MODE": "ONNX Model Loaded (Inference Only)",
        "LBL_PROMPT_TITLE": "YOLO-World Prompt:",
        "TIP_PROMPT_INPUT": "Enter class names separated by comma for Zero-Shot detection. E.g.: giant panda, bear",
        "PH_PROMPT": "e.g. giant panda, safety helmet",
        # ==== 以下为语言统一新增 key (en) ====
        "TTL_ERROR": "Error",
        "TTL_WARNING": "Warning",
        "TTL_SUCCESS": "Success",
        "TTL_CONFIRM": "Confirm",
        "TTL_INFO": "Info",
        "TTL_UPDATE": "Update",
        "TTL_CLASSES_UPDATED": "Classes Updated",
        "TTL_CRASH": "Crash",
        "TTL_ONNX": "ONNX Mode",
        "TTL_STOP_TRAINING": "Stop Training",
        "TTL_SELECT_EXPORT_DIR": "Select Export Dir",
        "TTL_SAVE_COCO": "Save COCO JSON",
        "TTL_SELECT_JSON": "Select JSON",
        "TTL_SELECT_XML_DIR": "Select XML Folder",
        "TTL_SELECT_MODEL": "Select Model",
        "TTL_SELECT_DATASET": "Select Dataset Root",
        "TTL_CLUSTER_DONE": "Clustering Done",
        "TTL_CLUSTER_FAIL": "Clustering Failed",
        "TTL_REMOVE_CONFIRM": "Confirm Removal",
        "FMT_MAP50": "mAP50\n{0}",
        "FMT_LOSS": "Loss\n{0}",
        "MON_MAP50": "mAP50",
        "MON_LOSS": "Loss",
        "MON_EPOCH": "Epoch",
        "MON_EPOCH_FMT": "{0} / {1}",
        "MON_BADGE_READY": "Ready",
        "MON_BADGE_TRAINING": "Training",
        "MON_BADGE_DONE": "Done",
        "MON_BADGE_FAILED": "Failed",
        "FMT_EPOCH": "Epoch {0}/{1}",
        "FMT_RUNTIME": "Runtime: {0:.4f} h",
        "FMT_LOG_EPOCH": "[Ep {0}/{1}] mAP: {2:.3f} | Loss: {3:.3f}",
        "FMT_DONE_IN": "Done in {0:.4f} h",
        "FMT_STATUS_TRAINING": "Training: {0} · Epochs {1} · Freeze {2}",
        "FMT_ROUND_REP_PROGRESS": "Round {0} reps: {1}/{2} labeled",
        "FMT_ROUND_QUOTA": "Round {0}: {1}/{2} labeled (reps {3} + extra {4}) · {5} to go",
        "FMT_ROUND_MISSING": " · pending: {0}",
        "FMT_ROUND_REPS_DONE": "Round {0} reps all labeled · click [Start Training] or wait for dialog",
        "MSG_ROUND_WAIT_TRAINING": "Round {0} labeling is complete, but round {1} is still training.\n\nTo keep the two runs from overwriting each other, this round's setup will open automatically once the current run finishes. Your labels are already saved — nothing more to do.",
        "FMT_ROUND_WAIT_TRAINING": "Round {0} ready · starts automatically when the current run ends",
        "FMT_CLUSTER_SAVED": "Generated {0} diverse clusters",
        "FMT_LABEL_SETUP_UPDATED": "Label setup updated: {0}",
        "FMT_ROUND_ALL_DONE": "Round {0} reps all labeled · ready to train",
        "FMT_ROUND_ACTIVE": "Round {0} · label {1} cluster reps (full list shown, reps on top)",
        "FMT_FULL_LIST_RESTORED": "Full list restored ({0} images) · manual labeling or training",
        "FMT_REMAINING_NO_CLUSTER": "{0} remaining unlabeled, no clustering needed.",
        "FMT_REMAINING_MANUAL": "{0} remaining unlabeled, please finish manually.",
        "FMT_ROUND_DONE_TITLE": "Round {0} training done — next round labeling",
        "FMT_RECLUSTER_STATUS": "Re-clustering · target {0} clusters...",
        "FMT_RECLUSTER_FEATURES": "Re-clustering · target {0} · extracting features...",
        "FMT_RECLUSTER_THRESHOLD": "Re-clustering · threshold {0} · generating clusters...",
        "FMT_ROUND_CLUSTERED": "Round {0} · threshold {1} {2} clusters",
        "FMT_RECLUSTER_FAILED": "Re-clustering failed: {0}",
        "FMT_REMOVED_DUPS": "Removed {0} duplicates, dataset now has {1} images",
        "FMT_DIVERSE_ORDER": "Sorted by diversity, first {0} are representative",
        "FMT_LIST_STATS": "{0} total · {1} labeled · {2} pending",
        "FMT_FILE_REP": "[Rep#{0} manual] {1}",
        "FMT_FILE_REP_TIP": "Cluster#{0} · representative · prioritize manual labeling",
        "FMT_FILE_AI": "[Cluster#{0} AI-pending] {1}",
        "FMT_FILE_AI_TIP": "Cluster#{0} · auto-labeled by AI after training",
        "PH_FIND_IMAGE": "Find image… (Enter jumps to first match)",
        "TIP_FIND_IMAGE": "Filter the image list by file name; press Enter to jump to the first match",
        "FMT_LIST_FILTER": "filtered {0}/{1}",
        "FMT_FILE_UNGROUPED": "[ungrouped] {0}",
        "FMT_ROUND_PRODUCT": "· Round {0} artifact",
        "FMT_ROUND_MAP": "· mAP {0:.3f}",
        "MSG_STATUS_DRAW_MODE": "Draw mode: drag to create box, auto-return to edit (R toggle)",
        "MSG_STATUS_EDIT_MODE": "Edit mode: click/drag boxes to adjust · press R for new box (R toggle)",
        "MSG_STATUS_STOPPED": "Stopped",
        "MSG_USER_STOPPED": "!!! User stopped training !!!",
        "MSG_STATUS_EXPORTING_XML": "Exporting XML...",
        "MSG_STATUS_EXPORT_XML_DONE": "Export XML Done",
        "MSG_STATUS_EXPORTING_JSON": "Exporting JSON...",
        "MSG_STATUS_EXPORT_JSON_DONE": "Export JSON Done",
        "MSG_STATUS_IMPORTING": "Importing...",
        "MSG_STATUS_IMPORT_DONE": "Import Done: {0} files",
        "MSG_EXPORT_FAILED": "Export Failed: {0}",
        "MSG_IMPORT_FAILED": "Import Failed: {0}",
        "MSG_LOADING_TRAINED": "Loading Trained: {0} ...",
        "MSG_LOADING_BASE": "Downloading/Loading Base: {0} ...",
        "MSG_LOAD_FAILED": "Load Failed:\n{0}",
        "MSG_BTN_ONNX_NOTRAIN": "ONNX (No Train)",
        "MSG_MODEL_LOADED_SUCCESS": "Model Loaded: {0}\nMode: Recursive",
        "MSG_STATUS_MOVED_JUNK": "Moved to Junk: {0}",
        "MSG_MOVE_FAILED": "Move failed:\n{0}",
        "MSG_STATUS_NO_IMAGES": "No images left",
        "MSG_IMAGES_FOLDER_NOT_FOUND": "Images folder not found!",
        "MSG_NO_IMAGES_FOUND": "No images found in folder!",
        "MSG_END_OF_LIST": "End of list",
        "MSG_NO_ANNOTATED_DATA": "No annotated data.",
        "MSG_STATUS_TRAINING": "Training...",
        "MSG_STATUS_INITIALIZING": "Initializing...",
        "MSG_STATUS_STARTING": "Starting...",
        "MSG_LOG_TRAIN_CONNECTED": ">>> Training process connected...",
        "MSG_LOG_MODEL_SAVED": ">>> Model saved: {0}",
        "MSG_TRAINING_DONE": "Training Done!\nSaved: {0}",
        "TTL_TRAIN_REPORT": "Training Complete",
        "MSG_TRAIN_REPORT": "Round {0} training complete\n\nTraining images: {1}\nmAP50: {2:.3f}\nTime: {3:.1f} min\nModel: {4}",
        "MSG_DATA_YAML_FAILED": "Failed to write data.yaml — training did not start: {0}",
        "TTL_TRAIN_SUMMARY": "Training Summary",
        "SUM_DATASET": "Dataset: {0} images · all labeled ✓",
        "SUM_ROUNDS": "Rounds: {0} total (round {1} ~ {2})",
        "SUM_BEST": "Best model: {0} · round {1} · mAP {2:.3f}",
        "SUM_DEPLOYED": "Deployed: {0} (highest mAP, auto)",
        "SUM_TH_ROUND": "Round",
        "SUM_TH_TIME": "Time",
        "SUM_TH_MODEL": "Model",
        "SUM_TH_IMAGES": "Images",
        "SUM_TH_DURATION": "Min",
        "SUM_TOTAL_TIME": "Total training time: {0} min",
        "SUM_FOOTER": "The label → train → relabel loop is complete. Models are saved in the weights folder.",
        "SUM_BTN_CLOSE": "Close",
        "SUM_BOXES": "Boxes: {0} total · {1} classes",
        "SUM_BOXES_TITLE": "Bounding boxes by class",
        "SUM_TH_CLASS": "Class",
        "SUM_TH_BOXES": "Boxes",
        "SUM_TH_SHARE": "Share",
        "MSG_STATUS_ERROR": "Error",
        "MSG_STATUS_FAILED": "Failed",
        "MSG_LOG_ERROR": "!!! Error: {0}",
        "MSG_NEW_CLASSES": "New classes: {0}",
        "MSG_SKIPPED_CLASSES": "Skipped invalid class names (shorter than 2 chars or illegal characters); no class was created for: {0}",
        # dialogs.py 补充
        "DLG_PH_CLASS": "Class Name",
        "DLG_BTN_GROUP": "Group ID",
        "DLG_PH_DESC": "Description (Optional)",
        "DLG_CHK_DIFFICULT": "useDifficult",
        "DLG_COMBO_SELECT": "--- Select ---",
        "DLG_PH_CLASS_EXAMPLES": "person, car, ...",
        "LBLST_TITLE": "Label Setup — AI-assisted",
        "LBLST_HEADER": "Label Setup\nDefine dataset classes and choose whether AI assists labeling.",
        "LBLST_DET_TRAINED": "Detected: dataset has a trained model\n Use it to auto pre-label remaining images (recommended), just review and fix.",
        "LBLST_DET_COCO": "Detected: {0} of {1} classes overlap COCO common classes ({2:.0f}%) — [{3}]\n Model can recognize these, AI pre-labeling recommended.",
        "LBLST_DET_NOMATCH": "Detected: classes [{0}] have no COCO overlap\n Niche dataset, AI quality poor — manual labeling recommended (can enable manually).",
        "LBLST_CHK_AI": "Use AI pre-label assist (YOLO-World first round / trained model later)",
        "LBLST_LBL_CLASSES": "Classes (comma separated):",
        "LBLST_PH_CLASSES": "person, car, ...",
        "LBLST_LBL_COCO": "Quick add from COCO:",
        "LBLST_BTN_CLEAR": "Clear",
        "LBLST_BTN_START": "Start Labeling",
        "LBLST_BTN_CANCEL": "Cancel",
        "LBLST_BTN_MOVE_UP": "Move Up",
        "LBLST_BTN_MOVE_DOWN": "Move Down",
        "LBLST_BTN_RENAME": "Rename",
        "LBLST_BTN_DELETE": "Delete",
        "LBLST_BTN_ADD": "Add",
        "MSG_RENAME_TITLE": "Rename Class",
        "MSG_RENAME_PROMPT": "Enter new name:",
        "MSG_CLASS_EXISTS": "Class already exists",
        "MSG_CLASS_EMPTY": "Classes cannot be empty",
        "MSG_DELETE_CLASS_CONFIRM": "Delete class \"{0}\"?\nExisting boxes of this class will be removed.",
        "MSG_CLASS_MAPPED": "Classes updated:\nRemapped {0} label files, removed {1} boxes.",
        "MSG_CLASS_CHANGED_TRAIN": "Classes changed; the trained model no longer matches.\nRetrain before using AI pre-labeling.",
        "CLN_TITLE": "Data Cleaning Wizard",
        "CLN_TITLE_DEDUP": "Duplicate Removal",
        "CLN_TITLE_CLUSTER": "Diversity Clustering",
        "CLN_STEP1_ONLY": "Remove exact duplicate images",
        "CLN_BTN_FINISH_DEDUP": "Finish Dedup",
        "CLN_BTN_PREV": "Previous",
        "CLN_BTN_NEXT": "Next",
        "CLN_BTN_FINISH": "Finish, Start Labeling",
        "CLN_BTN_CANCEL": "Cancel",
        "CLN_STEP1_TITLE": "Step 1: Remove exact duplicates\nDetects byte-level, pixel-level, and rotated/flipped variants. (Fixed perceptual hash, no model needed)",
        "CLN_BTN_SCAN": "Start Scan",
        "CLN_BTN_CONFIRM_REMOVE": "Confirm Remove Selected",
        "CLN_BTN_SKIP": "Skip, Keep All",
        "CLN_STEP2_TITLE": "Step 2: Configure clustering\nGroup remaining images by similarity, pick 1 rep per group to label first. After training, AI auto-labels the rest.",
        "CLN_LBL_FEATURE_MODEL": "Feature Model:",
        "CLN_LBL_THRESHOLD": "Similarity Threshold:",
        "CLN_LBL_THRESHOLD_HINT": "(≥ this similarity groups together)",
        "CLN_THRESHOLD_EXPLAIN": "Higher threshold finer groups (more clusters); lower coarser.\nE.g. 0.85 = images with ≥85% similarity group together.",
        "CLN_BTN_CLUSTER": "Start Clustering",
        "CLN_STEP3_TITLE": "Step 3: Cluster Result Preview",
        "CLN_GPU_NONE": "No discrete GPU (integrated)",
        "CLN_GPU_UNKNOWN": "Unknown",
        "CLN_REC_GPU": "Discrete GPU detected — recommend ResNet-50 (GPU)",
        "CLN_REC_RAM": "Plenty of RAM (≥16GB) — recommend EfficientNet-B0 (more accurate)",
        "CLN_REC_LOWMEM": "Low memory — recommend MobileNetV3 (fastest)",
        "CLN_HARDWARE_FMT": "Detected: {0} · {1:.0f}GB RAM\n {2}",
        "CLN_STEP2_1": "Step 1 of 2: Configure clustering",
        "CLN_STEP2_2": "Step 2 of 2: Cluster Result Preview",
        "CLN_STEP3_1": "Step 1 of 3: Remove exact duplicates",
        "CLN_STEP3_2": "Step 2 of 3: Configure clustering",
        "CLN_STEP3_3": "Step 3 of 3: Cluster Result Preview",
        "CLN_MSG_FIRST_REMOVE": "Please confirm removal or skip first.",
        "CLN_MSG_FIRST_CLUSTER": "Please finish clustering first.",
        "CLN_MSG_LOAD_DATASET": "Please load a dataset first!",
        "CLN_STATUS_SCANNING": "Scanning for duplicates...",
        "CLN_STATUS_SCAN_DONE": "Scan complete",
        "CLN_L1": "L1 Byte-level",
        "CLN_L2": "L2 Pixel-level",
        "CLN_L3": "L3 Rotated/Reflected",
        "CLN_STATS_TOTAL": "Total images: {0} | Elapsed: {1:.1f}s",
        "CLN_DUP_FOUND": "Found {0} duplicate groups",
        "CLN_DUP_FOUND_TAIL": "Total {0} to remove, {1} reps kept",
        "CLN_NO_DUP": "No duplicates found — proceed to next step.",
        "CLN_GROUP_FMT": "Group {0}: {1} {2}",
        "CLN_BLURRY": "Blurry images (low quality): {0}",
        "CLN_MSG_NO_SELECTION": "No duplicate images selected.",
        "CLN_REMOVE_CONFIRM_BODY": "Move {0} duplicate images to _removed_duplicates/?\n{1}\n(Rep kept per group, not physically deleted, recoverable)",
        "CLN_REMOVED_MARK": "Removed",
        "CLN_REMOVED_STATUS": "{0} marked removed. Click \"Next\" to continue.",
        "CLN_SKIPPED_STATUS": "Skipped removal, all images kept. Click \"Next\" to continue.",
        "CLN_REMAINING_FMT": "Images to cluster: {0}",
        "CLN_REMAINING_REMOVED": "({0} removed)",
        "CLN_CLUSTER_REF": "Reference: {0} images ~{1} clusters (≈5%)\nLabel ~{1} reps in round 1 (1 per group)",
        "CLN_MSG_TOO_FEW": "Too few images to cluster.",
        "CLN_STATUS_CLUSTERING": "Clustering...",
        "CLN_STATUS_CLUSTERING_PROG": "Clustering... ({0}/{1})",
        "CLN_STATUS_TEXT_HEAD": "{0} groups, all {1} images assigned.",
        "CLN_STATUS_TEXT_MAX": "Largest group {0:.0f}% — bigger area = more images in group.",
        "CLN_STATUS_TEXT_REF": "Reference: ~{0} clusters (≈5% of {1}), label ~{0} reps in round 1.",
        "CLN_STATUS_TEXT_DEVIATION": "\n {0} clusters deviate from reference {1} — adjust threshold and re-cluster.",
        "CLN_TREEMAP_ITEM_3": "Cl{0}\n{1}\n{2:.0f}%",
        "CLN_TREEMAP_ITEM_2": "Cl{0}\n{1:.0f}%",
        "CLN_TREEMAP_ITEM_1": "Cl{0}",
        "CLN_TREEMAP_TITLE": "Cluster distribution ({0} groups, {1} images)",
        "CLN_MSG_ERROR": "Operation failed:\n{0}",
        "CLN_PHASE_CACHE": "Reusing cached features ...",
        "CLN_PHASE_EXTRACT": "Extracting features ...",
        "CLN_PHASE_THRESH": "Auto-searching threshold {0:.3f} ...",
        "CLN_EMBED_MOBILE": "MobileNetV3 (Fastest, CPU-friendly)",
        "CLN_EMBED_EFFICIENT": "EfficientNet-B0 (More accurate)",
        "CLN_EMBED_RESNET": "ResNet-50 (Strongest, GPU recommended)",
        # training_dialog
        "TD_TITLE": "Training Setup",
        "TD_HEADER_FIRST": "First round · {0}/{1} labeled\nStart the first model training",
        "TD_HEADER_ROUND": "Round {0} triggered\n{1} newly labeled · {2}/{3} labeled in dataset",
        "TD_HEADER_LAST": "\nPrevious model: {0}{1}{2}",
        "TD_LBL_MODEL": "Model:",
        "TD_HINT_ITERATE": "Iterative training on previous model (auto-loads best weights)",
        "TD_HINT_MODEL_PICK": "Best mAP model selected by default — you can also pick a base model (e.g. yolo11n)",
        "TD_GRP_PARAMS": "Parameters",
        "TD_LBL_EPOCHS": "Epochs:",
        "TD_LBL_FREEZE": "Freeze Layers:",
        "TD_BTN_TRAIN": "Start Training",
        "TD_BTN_CANCEL": "Cancel",
        "TD_BTN_BROWSE": "Browse…",
        "TD_TIP_BROWSE": "Pick a custom model weights file (.pt/.pth) to start training from",
        "TD_CUSTOM_PREFIX": "Custom: {0}",
        # training_worker
        "WRK_INIT_ENV": "Initializing training environment...",
        "WRK_START_TORCH": "Starting PyTorch Training: {0}",
        "WRK_START_YOLO": "Starting YOLO Training: {0}",
        "WRK_LOAD_MODEL": "Loading model: {0}",
        "WRK_DOWNLOAD_WEIGHTS": "Downloading model weights for {0}...",
        "WRK_USE_LOCAL": "Using local model: {0}",
        "WRK_DOWNLOAD_ULTRALYTICS": "Downloading from ultralytics... (may need network)",
        "WRK_MODEL_LOAD_FAIL": "Model load failed: {0}. Try placing {1}.pt in project root.",
        "WRK_BEST_NOT_FOUND": "Training failed: best.pt not found",
        # inference_engine
        "INF_LOAD_ERROR": "Model Load Error: {0}",
        "INF_NO_DETECTIONS": "(no detections)",
        "INF_YOLO_FMT": "YOLO: {0} | {1:.1f}ms",
        "INF_FAILED": "Inference Failed",
        "FMT_SUGGEST_BOX": "Detected similar object {0} → suggestion box drawn, please fix the label",
        "MSG_NO_DETECTIONS": "No objects detected (0 predictions)",
        # model_wrappers
        "WRAP_LOAD_ERROR": "Load Error",
        "WRAP_CLASSIC_FOUND": "Classic Found: {0}",
        "WRAP_ONNX_FOUND": "ONNX Found: {0}",
        # data_cleaner phases
        "PHASE_DEDUP": "Exact hash dedup (SHA-256) ...",
        "PHASE_BLUR": "Blur detection ...",
        "PHASE_HASH": "Hashing ({0}) ...",
        "PHASE_EXTRACT_FEAT": "Extracting features ({0}) ...",
        "PHASE_EXTRACT": "Extracting ({0}) ...",
        "PHASE_INDEX": "Building search index ...",
        "MSG_STATUS_DONE": "Done",
        "MSG_CRASH_OPEN_LOG": "Open log: {0}\n{1}",
        "FMT_TARGET_CLUSTERS": "Target clusters:",
        "MSG_BTN_RECLUSTER": "Re-cluster and start labeling",
        "MSG_BTN_VIEW_ALL": "View all images",
        "MSG_NO_DATASET_LOADED": "No dataset loaded",
        "FMT_REMAINING_TOO_FEW": "{0} remaining unlabeled — need at least {1} to cluster",
        "BTN_LABEL_SETUP": "Label Setup",
        "BTN_SUMMARY": "Summary",
        "SUM_NO_HISTORY": "No training history yet",
        "BTN_IMPORT": "Import Labels",
        "BTN_EXPORT": "Export Labels",
        "BTN_MODEL": "Load Model",
        "BTN_LANG": "Language",
        "FMT_MAP50_SUFFIX": "· mAP50: {0:.3f}",
        "FMT_EPOCHS_SUFFIX": "· {0} epochs",
        "BTN_MODEL_OWN": "Load Own Model",
        "BTN_MODEL_OWN_FILE": "Choose File…",
        "BTN_MODEL_BASE": "Base Models",
        "BTN_MODEL_WORLD": "World Models (Zero-Shot)",
        "MSG_NO_TRAINED_MODEL": "(No trained models)",
        "LBL_AI_ASSIST": "AI Pre-label Assist",
        "TIP_AI_ASSIST": "When enabled, unlabeled images are pre-annotated by AI automatically",
        "LBL_COMPARE": "Model comparison (cyan)",
        "TIP_COMPARE": "When enabled the deployed model also runs on already-annotated images. Its predictions are drawn as cyan dashed boxes and are never written to the label file; moving or resizing one accepts it as a human annotation.",
    }
}


def get_lang():
    """Read current UI language from QSettings (usable in worker processes)."""
    try:
        from PyQt5.QtCore import QSettings
        lang = QSettings("KeenForgeAI", "KeenForge").value("language", "zh", type=str) or "zh"
        return lang if lang in TRANS else "zh"
    except Exception:
        return "zh"


def t(key, *args, **kwargs):
    """Translate a TRANS key with optional .format() args. Safe for subprocesses."""
    lang = get_lang()
    s = TRANS.get(lang, TRANS["zh"]).get(key, key)
    if args or kwargs:
        try:
            return s.format(*args, **kwargs)
        except Exception:
            return s
    return s


# Standard COCO class list
COCO_CLASSES = [
    "person", "bicycle", "car", "motorcycle", "airplane", "bus", "train", "truck", "boat", "traffic light",
    "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat", "dog", "horse", "sheep", "cow",
    "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella", "handbag", "tie", "suitcase", "frisbee",
    "skis", "snowboard", "sports ball", "kite", "baseball bat", "baseball glove", "skateboard", "surfboard",
    "tennis racket", "bottle", "wine glass", "cup", "fork", "knife", "spoon", "bowl", "banana", "apple",
    "sandwich", "orange", "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair", "couch",
    "potted plant", "bed", "dining table", "toilet", "tv", "laptop", "mouse", "remote", "keyboard", "cell phone",
    "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors", "teddy bear",
    "hair drier", "toothbrush"
]
